"""Initial schema: baseline snapshot of all SQLAlchemy models.

Revision ID: 0001
Revises:
Create Date: 2026-09-06

This is the genesis migration: it materializes the current ORM metadata
(26 tables) and is the baseline that future autogenerated revisions will diff
against.
"""

from alembic import op
from app.infrastructure.database.base import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Import all models so the full metadata is present
    import app.infrastructure.database.models  # noqa: F401

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    import app.infrastructure.database.models  # noqa: F401

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
